import { glob, realpath, readFile, mkdir, writeFile, unlink, access } from 'node:fs/promises';
import path from 'node:path';
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';
import postcssUrl from 'postcss-url';

const generatedHeader = '/* Generated by IgnIt CSS pipeline. */\n';
const sharedEntry = 'static/css/_src/style.css';
const pagePattern = 'content/**/assets/css/_src/style.css';

async function exists(file) {
  try {
    await access(file);
    return true;
  } catch (error) {
    if (error.code === 'ENOENT') return false;
    throw error;
  }
}

export async function discover(root) {
  const shared = path.join(root, sharedEntry);
  if (!(await exists(shared))) {
    throw new Error(`Missing shared CSS entry: ${shared}`);
  }
  const pages = [];
  for await (const relative of glob(pagePattern, { cwd: root })) {
    if (
      relative
        .split(path.sep)
        .slice(1, -4)
        .some((part) => part.startsWith('_'))
    )
      continue;
    const source = path.join(root, relative);
    const bundle = path.resolve(path.dirname(source), '../../..');
    if (!(await exists(path.join(bundle, 'index.md')))) {
      throw new Error(`Page CSS has no owning index.md: ${source}`);
    }
    pages.push(source);
  }
  return [shared, ...pages.sort()];
}

export function buildCss(root = process.cwd()) {
  // Tailwind retains scanner candidates between runs. Fresh workers make full builds reproducible.
  return new Promise((resolve, reject) => {
    const worker = new Worker(new URL(import.meta.url), { workerData: { cssRoot: root } });
    worker.once('message', (result) => {
      if (result.error)
        reject(Object.assign(new Error(result.error), { dependencies: result.dependencies }));
      else resolve(result);
    });
    worker.once('error', reject);
    worker.once('exit', (code) => {
      if (code !== 0) reject(new Error(`CSS compiler exited with status ${code}`));
    });
  });
}

async function compileCss(root) {
  root = await realpath(root);
  const entries = await discover(root);
  const dependencies = new Set(entries);
  const outputs = new Set();
  const compiled = [];
  for (const source of entries) {
    const output = path.resolve(path.dirname(source), '../style.generated.css');
    const directives = [];
    if (source !== entries[0]) {
      directives.push(`@reference ${JSON.stringify(entries[0])};`);
    }
    directives.push(`@import ${JSON.stringify(source)};`);
    if (source === entries[0]) {
      for (const folder of ['content', 'templates']) {
        directives.push(`@source ${JSON.stringify(path.join(root, folder))};`);
      }
    }
    let currentResult;
    let result;
    try {
      result = await postcss([
        {
          postcssPlugin: 'capture-dependencies',
          Once(_, context) {
            currentResult = context.result;
          },
        },
        tailwindcss({ base: root, optimize: false, transformAssetUrls: true }),
      ]).process(directives.join('\n'), { from: output, to: output });
    } catch (error) {
      for (const message of currentResult.messages) {
        if (message.type === 'dependency') dependencies.add(message.file);
        if (message.type === 'dir-dependency') dependencies.add(message.dir);
      }
      throw Object.assign(error, { dependencies: [...dependencies] });
    }
    for (const message of result.messages) {
      if (message.type === 'dependency') dependencies.add(message.file);
      if (message.type === 'dir-dependency') dependencies.add(message.dir);
    }
    const published = await postcss([
      postcssUrl({
        url: (asset) => {
          if (/^(?:[a-z]+:|\/|#)/i.test(asset.url)) return asset.url;
          if (source !== entries[0]) {
            const bundle = path.resolve(path.dirname(source), '../../..');
            if (!asset.absolutePath.startsWith(bundle + path.sep)) {
              throw new Error(
                `Page CSS relative asset is outside its owning bundle: ${source} -> ${asset.absolutePath}`,
              );
            }
          }
          const relative = path.relative(root, asset.absolutePath).split(path.sep);
          if (relative[0] === 'themes' && relative[2] === 'static') {
            const target = path.join(root, 'static', ...relative.slice(3));
            return (
              path.relative(path.dirname(output), target).split(path.sep).join('/') +
              asset.search +
              asset.hash
            );
          }
          if (
            source === entries[0] &&
            !asset.absolutePath.startsWith(path.join(root, 'static') + path.sep)
          ) {
            throw new Error(
              `Shared CSS asset is outside the merged static tree: ${asset.absolutePath}`,
            );
          }
          return asset.url;
        },
      }),
    ])
      .process(result.css, { from: output, to: output })
      .catch((error) => {
        throw Object.assign(error, { dependencies: [...dependencies] });
      });
    outputs.add(output);
    compiled.push([output, generatedHeader + published.css + '\n']);
  }
  for (const [output, css] of compiled) {
    await mkdir(path.dirname(output), { recursive: true });
    if (!(await exists(output)) || (await readFile(output, 'utf8')) !== css) {
      await writeFile(output, css);
    }
  }
  for await (const relative of glob('content/**/assets/css/style.generated.css', {
    cwd: root,
  })) {
    const output = path.join(root, relative);
    if (!outputs.has(output) && (await readFile(output, 'utf8')).startsWith(generatedHeader)) {
      await unlink(output);
    }
  }
  return { outputs, dependencies };
}

export async function watchCss(root = process.cwd(), report = console.log) {
  const { default: watcher } = await import('@parcel/watcher');
  root = await realpath(root);
  const subscriptions = new Map();
  const dependencies = new Set();
  let closed = false;
  let running = false;
  let pending = false;
  let timer;
  async function rebuild() {
    if (running) {
      pending = true;
      return;
    }
    running = true;
    do {
      pending = false;
      try {
        const result = await buildCss(root);
        dependencies.clear();
        for (const dependency of result.dependencies) dependencies.add(dependency);
        for (const dependency of dependencies) {
          if (!dependency.startsWith(root + path.sep) && (await exists(dependency))) {
            await subscribe(path.dirname(dependency));
          }
        }
        const { outputs } = result;
        report(`Built ${outputs.size} CSS stylesheet(s)`);
      } catch (error) {
        for (const dependency of error.dependencies ?? []) {
          dependencies.add(dependency);
          if (!dependency.startsWith(root + path.sep) && (await exists(dependency))) {
            await subscribe(path.dirname(dependency));
          }
        }
        report(error.toString());
      }
    } while (pending);
    running = false;
  }
  async function subscribe(directory) {
    if (subscriptions.has(directory)) return;
    const subscription = await watcher.subscribe(
      directory,
      (error, events) => {
        if (error) {
          report(error.toString());
          return;
        }
        if (
          closed ||
          !events.some(
            ({ path: file }) =>
              !file.endsWith('.generated.css') &&
              (dependencies.has(file) || /\.(css|md|html)$/.test(file)),
          )
        )
          return;
        clearTimeout(timer);
        timer = setTimeout(rebuild, 50);
      },
      { ignore: ['**/node_modules/**', '**/.git/**', '**/public/**'] },
    );
    subscriptions.set(directory, subscription);
  }
  await subscribe(root);
  await rebuild();
  return async () => {
    closed = true;
    clearTimeout(timer);
    await Promise.all(
      [...subscriptions.values()].map((subscription) => subscription.unsubscribe()),
    );
  };
}

if (!isMainThread) {
  try {
    parentPort.postMessage(await compileCss(workerData.cssRoot));
  } catch (error) {
    parentPort.postMessage({ error: error.toString(), dependencies: error.dependencies ?? [] });
  }
} else if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  try {
    if (process.argv.includes('--watch')) {
      await watchCss();
    } else {
      const { outputs } = await buildCss();
      console.log(`Built ${outputs.size} CSS stylesheet(s)`);
    }
  } catch (error) {
    console.error(error.toString());
    process.exitCode = 1;
  }
}
